### ISSUE TITLE
Incorrect return value for update in readme?

### ISSUE THREAD

**Issue by jonaskello** [andrejewski/raj-react#24]
In the readme the example is:

```js
 update (message, model) {
    return model
  },
```

I think it should be this instead:

```js
 update (message, model) {
    return [model]
  },
```

Looking at the code for raj, it seems it is not possible to return non-tuple values from update?

**Comment by jonaskello** [comment]
Nitpick: The use of the word `model` here is a bit confusing since the main raj package calls the same thing `state`. In redux it is called `state`, in elm it is called `model`. I think raj should pick one and stick with it in all it's packages :-).

**Comment by andrejewski** [comment]
@jonaskello I do use `model` and `state` inconsistently. From now on, I'll stick to using `state` for the libraries I manage to match the framework's naming. In my apps, I do prefer `model` because of the alliteration of `msg` and `model`, but I'll think about changing there too.

**Comment by jonaskello** [comment]
Yes, having consistence between the main packages is nice. I understand wanting to use use other names in own applications. As I explore raj I find myself calling the `Message` types `Action` because I've worked a lot in redux applications.
